services:
  redis-src:
    image: redis/redis-stack:7.2.0-v9
    environment:
      - REDIS_ARGS=--save 20 1 --loglevel warning --notify-keyspace-events KEA
    ports:
      - "6379:6379"
      - "8001:8001"
    networks:
      - redisnet

  redis-dst:
    image: redis/redis-stack:7.2.0-v9
    environment:
      - REDIS_ARGS=--save 20 1 --loglevel warning --notify-keyspace-events KEA
    ports:
      - "6380:6379"
      - "8002:8001"
    networks:
      - redisnet

  seeder:
    build: .
    depends_on:
      - redis-src
    environment:
      - REDIS_HOST=redis-src
      - REDIS_PORT=6379
    networks:
      - redisnet
    command: python seed_data.py

  riot-migrator:
    image: riotx/riot:v4.3.0
    depends_on:
      seeder:
        condition: service_completed_successfully
      redis-dst:
        condition: service_started
    networks:
      - redisnet
    volumes:
      - ./riot_migrate.sh:/workspace/riot_migrate.sh
    entrypoint: ["/bin/sh", "/workspace/riot_migrate.sh"]

networks:
  redisnet:
